config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles do
    resources :comments
  end
  resources :contacts
  root to: 'pages#index'

  # If you want a localhost:3000/hello to route to the contacts page then:
  # get 'hello', to: 'pages#contact'
  get 'pages/contact'
  get 'pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validate_presence_of :name
  validate_presence_of :email
  validate_presence_of :message

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
    @last5 = Article.last(4)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    # @article = Article.new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    # @article = Article.new(article_params)
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:body))
    @comment.user_id = current_user.id if current_user

    if @comment.save
      redirect_to article_path(@article), notice: "Your comments has been saved."
    else
      redirect_to 'new'
    end
  end

  def update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:body))
      redirect_to article_path(@article), notice: "Your comment has been updated."
    else
      render 'edit'
    end
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), notice: "Your comment has been deleted."
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path
      name = params[:contact][:name]
      email = params[:contact][:email]
      message = params[:contact][:message]
      ContactMailer.contact_email(name, email, message).deliver
      flash[:success] = "Thank You for the message, we will be in contact soon."
    else
      redirect_to pages_contact_path
      flash[:danger] = "Oops, there was a problem! Please fill out all the fields."
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def index
    if current_user
      redirect_to articles_path
    end
    @articles = Article.last(4)
  end

  def contact
    @contact = Contact.new
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(
        :email,
        :password,
        :password_confirmation,
        :username,
        :firstname,
        :lastname
        )
  end

  def account_update_params
    params.require(:user).permit(
        :email,
        :password,
        :password_confirmation,
        :username,
        :firstname,
        :lastname,
        :current_password
        )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :title %>

    <%= f.input :body %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">

  <!-- Blog article Content Column -->
  <div class="col-lg-8">
    <% @articles.each do |article| %>

      <!-- Blog article -->

      <!-- Title -->
      <h4 style="font-size: 45.5px;"><%= link_to article.title, article %></h4>
      <!-- Date/Time -->
      <p><span class="glyphicon glyphicon-time"></span>
      </p>

      <!-- Author -->
      <p>
        Article By:<strong> <%= article.user.username %></strong>
      </p>
      <hr>

      <!-- articleed Comments -->

      <!-- Comment -->
    <% end %>
    <%= link_to "New article", new_article_path, class: "btn btn-default btn-xs" %>
    </div>

  <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">
    <div class="well">
      <h4>Recent articles</h4>
      <% @last5.each do |p| %>
      Created by: <%= p.user.username %><br />
      <strong><%= link_to p.title, p %></strong>
      <p><%= truncate(p.body) %></p>
      <% end %>
    </div>
  </div>
</div>
<%= will_paginate @articles %>
<br>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-lg-8">

        <!-- Blog Post -->

        <!-- Title -->
        <h1 style="font-size: 62.5px;">
         <%= @article.title %>
        </h1>

        <!-- Author -->
        <p class="lead">
          <%= @article.user.username %>
        </p>

        <hr>

        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> Was Posted:


        <hr>

        <!-- Preview Image -->


        <!-- Post Content -->
          <%= @article.body %>

        <hr>

        <!-- Blog Comments -->
<%= render @article.comments %>
        <!-- Comments Form -->

        <%= render 'comments/form' %>
        <div class="well">


<h4></h4>


        </div>

        <hr>

        <!-- Posted Comments -->

        <!-- Comment -->



    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

        <!-- Blog Search Well -->


        <!-- Blog Categories Well -->


        <!-- Side Widget Well -->
        <div class="well">
          <h4></h4>

        </div>

    </div>

</div>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<div class="media">
  <div class="pull-left">

  <%= comment.user.username %>

  </div>
  <div class="media-body">
    <p class="media-heading pull-right">

      <%= time_ago_in_words(comment.created_at) %>

    </p><br />
    <%= comment.body %>
  </div>
</div>
<%= link_to "Edit", edit_article_comment_path(comment.article, comment) %>
<%= link_to "Delete", [comment.article, comment], method: :delete, data: { confirm: "Are you Sure?" } %>

app/views/comments/_form.html.erb
<%= simple_form_for ([@article, @article.comments.build]) do |f|%>

<%= f.input :body %>
<%= f.submit "Post your comment" %>

<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment</h1>
<%= simple_form_for([@article, @comment]) do |f| %>
<%= f.input :body %>
<%= f.submit %>
<% end %>

app/views/layouts/_foot.html.erb
<footer class="footer-distributed navbar-fixed-bottom">
  <div class="footer-right">
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>
  </div>
  <div class="footer-left">
    <p class="footer-links">
      ·
      <%= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>
      ·
      <%= link_to "About Us", pages_about_path, class: "page-scroll" %>
      ·
    </p>
    <p> </p>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Roan's Articles", root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


          <ul class="nav navbar-nav navbar-right">

            <li><%= link_to "Contact Us", pages_contact_path %></li>
            <li><%= link_to "About Us", pages_about_path %></li>
            <li><%= link_to "View Articles", articles_path %></li>
            <% if !current_user %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li><%= link_to "Edit My Profile", edit_user_registration_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roan's Articles</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= bootstrap_flash %>
    <div class='container'>
          <%= yield %>
    </div>
    <%= render 'layouts/foot' %>
  </body>
</html>

app/views/pages/_mailer.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= simple_form_for @contact do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :message %>
      <%= f.submit "Get in touch!", class: "btn btn-info" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>About Us</h1>
    <p class="lead">Test Text</p>
    <ul class="list-unstyled">
      <li>List Item</li>
      <li>List Item 2</li>
    </ul>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Contact Us</h1>
    <p class="lead">Test Text</p>
    <ul class="list-unstyled">
      <li>List Item</li>
      <li>List Item 2</li>
    </ul>
  </div>
  <%= render 'pages/mailer' %>
</div>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-lg-8">
    <!-- Blog Post -->
    <!-- Title -->
    <div class="jumbotron">
      <h1>Welcome to Roan's Articles. </h1>
      <p>Awesome applications built with Rails!</p>
      <p>This was done for a course on Udemy</p>
    </div>
  </div>
  <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">
    <!-- Blog Categories Well -->
    <!-- Side Widget Well -->
    <div class="well">
      <h4>Recent Posts</h4>
      <% @articles.each do |a| %>
        Created by: <%= a.user.username %><br />
        <strong><%= link_to a.title, a %></strong>
        <p><%= truncate(a.body) %></p>
      <% end %>
    </div>
  </div>
</div>
<!-- /.row -->
<hr>